pipeline{
    agent any

    tools{
        maven 'M2_HOME'
    }

    stages{
        stage('sonar-scan'){
            steps{
                withSonarQubeEnv('SonarQube'){
                    sh 'mvn verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.projectKey=Niknak0890_geo-app'
                }
                
            }
        }

        stage("maven"){
            steps{
            sh 'mvn clean validate compile install test package'
        }

        }
        stage('upload artifact'){
            steps{
                sh 'curl -uadmin:AP8PYxTpmnyMe26bsUvyihFH7Sz -T\
                 target/bio*.jar\
                 "http://54.173.157.119:8081/artifactory/geolocation/geo/bio_${BUILD_ID}.jar"'
            }
        }
        stage('docker login'){
            steps{
                sh 'aws ecr get-login-password --region us-east-1 | \
                docker login --username AWS --password-stdin \
                486406605446.dkr.ecr.us-east-1.amazonaws.com'
            }
        }
        stage('docker image build'){
            steps{
                sh 'docker build -t utc-app-dev:v.${BUILD_ID} .'
                sh 'docker build -t utc-app-dev:latest .'
            }
        }
        stage('image tagging'){
            steps{
                 sh 'docker tag utc-app-dev:latest \
                486406605446.dkr.ecr.us-east-1.amazonaws.com/utc-app-dev:latest'
                 sh 'docker tag utc-app-dev:latest \
                486406605446.dkr.ecr.us-east-1.amazonaws.com/utc-app-dev:v.${BUILD_ID}'
            }
        }
        stage('upload/push image'){
            steps{
                sh 'docker push \
                486406605446.dkr.ecr.us-east-1.amazonaws.com/utc-app-dev:latest'
                sh 'docker push \
                486406605446.dkr.ecr.us-east-1.amazonaws.com/utc-app-dev:v.${BUILD_ID}'
            }
        }
    }   

}