pipeline{
    agent any

    tools{
        maven 'M2_HOME'
    }

    stages{
        stage('sonar-scan'){
            steps{
                withSonarQubeEnv('SonarQube'){
                    sh 'mvn verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.projectKey=Niknak0890_geo-app'
                }
                
            }
        }

        stage("maven"){
            steps{
            sh 'mvn clean validate compile install test package'
        }

        }
        stage('upload artifact'){
            steps{
                sh 'curl -uadmin:AP8PYxTpmnyMe26bsUvyihFH7Sz -T\
                 target/bio*.jar\
                 "http://ec2-34-204-101-177.compute-1.amazonaws.com:8081/artifactory/geolocation/geo/bio_${BUILD_ID}.jar"'
            }
        }
        stage('docker login'){
            steps{
                sh 'aws ecr get-login-password --region us-east-1 | \
                docker login --username AWS --password-stdin \
                486406605446.dkr.ecr.us-east-1.amazonaws.com'
            }
        }
    }
}